patient-service:
  build:
    context: ./patient-service
  container_name: patient-service
  depends_on:
    - postgres-db
  ports:
    - "4000:4000"
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/db
    SPRING_DATASOURCE_USERNAME: admin_user
    SPRING_DATASOURCE_PASSWORD: password
    SPRING_JPA_HIBERNATE_DDL_AUTO: update
    SPRING_SQL_INIT_MODE: always
